### ISSUE TITLE
Feature: Self Codes

### ISSUE THREAD

**Issue by worksofliam** [codefori/vscode-db2i#137]
**Part 1**

- [x] Ability to set self codes on a job
- [x] Ability to fetch error log for a job

**Part 2**

```sql
SELECT user_name, logged_time, logged_sqlstate, logged_sqlcode, matches, stmttext, 
       message_text, message_second_level_text 
  FROM qsys2.sql_error_log, lateral 
    (select * from TABLE(SYSTOOLS.SQLCODE_INFO(logged_sqlcode)))
where user_name = current_user
order by logged_time desc
```

* [x] New tree view for SELF logs
  * [x] Can only be shown when we have an SQL job running
  * [x] This view needs a button to clear the self code logs for the current user
  * [x] Manually refresh button
  * [x] Node style matches the following:

```
  // 01534 (181) - 15 hits, Values in date, time, or timestamp string not valid.
    // Hover: STMTTEXT \n\n---\n\nSECOND_LEVEL_TEXT
```

* [x] SQL job needs a option to set the level
  * [x] No longer setting by specific code
  * [x] Setting by: *ALL, *WARN, *ERROR, *NONE

```sql
set sysibmadm.selfcodes = '*ALL';  -- or *ERROR or *WARN or *NONE
```

* [x] Interval to fetch the SELF log
  1. [x] Run the provided statement to get the logs for the current user
  2. [x] Update the SELF log tree view with the new nodes based on the log data
* [x] We need a way to turn on/off the interval, which also means turning off and always hiding the view
* [ ] Ensure SELF Codes views and buttons only work on 7.4+
   * We have the version in `OSData`, we can just set a context value to enable/disable based on that
* Use decoration provider for hit count in SELF Code view

---

Look into how to incorporate this?

```
select a.*
  from QSYS2.SQL_ERROR_LOG l, lateral (
         select *
           from json_table(INITIAL_STACK, 'lax $.initial_stack[*]'
               columns(
                 ORDINAL_POSITION integer path 'lax $."ORD"',
                 PROGRAM_TYPE varchar(10) ccsid 37 path 'lax $."TYPE"',
                 PROGRAM_LIB  varchar(10) ccsid 37 path 'lax $."LIB"',
                 PROGRAM_NAME  varchar(10) ccsid 37 path 'lax $."PGM"',
                 MODULE_NAME  varchar(10) ccsid 37 path 'lax $."MODULE"',
                 PROCEDURE_NAME  varchar(128) ccsid 37 path 'lax $."PROC"',
                 STATEMENT_NUMBER  varchar(10) ccsid 37 path 'lax $."STMT"',
                 ACTIVATION_GROUP  varchar(10) ccsid 37 path 'lax $."ACTGRP"'
               )
             )
       ) a  
       
       where logged_sqlcode = -311; 
```

**Comment by ajshedivy** [comment]
Progress on UI portion:

![image](https://github.com/codefori/vscode-db2i/assets/50843283/84985c3d-f07b-49a8-a657-0b1c57b56281)
