### ISSUE TITLE
Feature: Visual Explain

### ISSUE THREAD

**Issue by worksofliam** [codefori/vscode-db2i#138]
**Part 1: API**

- [x] API to install Dove SQL procedure on the server in QTEMP. Accepts the statement and which mode (run and explain or explain without running) and returns the VE flat data (this would be run once when the user tries to use VE)
- [x] New APIs in vscode-db2i to invoke new Server Component
- [x] Unit tests for new APIs

**Part 2: UI**

- [x] Write code to convert VE flat data from API to nodes (this code was written by Liam and shared with Dave so far)
- [x] Implement new tree view which is only shown when VE is run from the client. The nodes in the tree match the new node structure from the flat data
- [x] When a node is clicked on, show another view of panel with the details of that node
- [x] New buttons to run VE based on the current statement (similar to the current runner)
    - [x] Button to have dropdown with two options: Run and Explain & Explain without running (Liam to do this)
    - https://github.com/gitkraken/vscode-gitlens/blob/main/package.json#L14358
- [x] Highlight important nodes
- [x] User configurable highlighting
- [x] Node details section headings
- [x] Icons for different explain nodes
- [x] Show scrolling result set when 'run and explain' is used (waiting for Server Component change)
- [x] Node detail tree needs to use parent/child nodes, expanded by default
- [x] Display node detail tree on initial display of the node tree
- [x] Reposition node detail tree to top when selection is made in the node tree
- [x] VS Code settings for visual explain

**Part 3: review**

- [ ] Review UI for nodes and node data
    - Meet with Ryan/Scott/Db people for opinions
    - Let them try have a vsix
    - Gather new requirements/changes based on feedback
- [ ] Review code
- [ ] Performance considerations

**Part 4: extras**

- [x] Highlighting priority
- [ ] Import and export of node data (or flat data?)
- [ ] Basic vs detail option in the Server Component
- [ ] Minimum vs optimise in the Server Component

**Comment by worksofliam** [comment]
Note from customer:

> Tim just showed the visual explain stuff in DB extension.
> Looks great. I have one question in the tree view can you add the timings ?

**Comment by davecharron** [comment]
> Note from customer:
> 
> > Tim just showed the visual explain stuff in DB extension.
> > Looks great. I have one question in the tree view can you add the timings ?

By 'timings' do they mean the attributes displayed on the links between nodes?

**Comment by worksofliam** [comment]
@davecharron I am guessing they mean this data on the VE node itself? Maybe we need a way to switch between these being displayed in the TreeItem `description` prop?

> Columns/fields i look at are
> processing time in ms
> cumulative time in ms
> rows selected in the step
